### PR TITLE
Add Python dependencies

### LINKED ISSUE #28: Load python dependencies from Kubeless UI
Migrated from https://github.com/kubeless/kubeless/issues/229.

Feature: Have a option to load python dependencies from Kubeless UI

### PR DESCRIPTION
**Pull request by kemcake**
Add an input to specify python dependencies

Fixes #28 

p96bm9istp

### CODE REVIEW

**Comment by sebgoa** [comment]
Do you have a solution for node.js functions ?

@andresmgot can you review ? thx

**Comment by andresmgot** [comment]
Hi there 👋,
Specifying the dependencies one by one will only work for Python. For Ruby or NodeJS it would be necessary to specify a Gemfile or a package.json and upload its content. Since the code disables the possibility of adding dependencies for those two languages I am fine with this PR as far as it has a follow up one in which we can specify those requirement files.

**Comment by kemcake** [comment]
Yes it seems to be another approach for node and ruby. Since python was the simplest one I wanted to start with this PR and yes following up with another PR for Node and Ruby.

**Comment by kemcake** [comment]
Closing in favor of 👉  #31

**Pull request closed without merging**
